name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2 # using minimum_zig_version from build.zig.zon

      - name: Verify Build
        run: zig build

      - name: Run Tests
        run: zig build test
